baseURL: http://gallery33.art/
title: Gallery 33


paginate: 20
enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
languageCode: "bg"
defaultContentLanguage: bg
defaultContentLanguageInSubdir: false

params:
  colors:
    # light
    base_bg: "#fdfcf9"
    base_bg_2: "#f7f6ed"
    base_bg_3: "#faebd7"
    base_text: "#0d042b"
    base_text_2: "#3b364c"
    primary_bg: "#0d042b"
    primary_bg_2: "#0d042b"
    primary_bg_3: "#0d042b"
    primary_text: "#fdfcf9"
    header_text: "#0d042b"
    logo_text: "#0d042b"

    # dark
    base_bg_dark: "#0b0326"
    base_bg_2_dark: "#150c32"
    base_bg_3_dark: "#251654"
    base_text_dark: "#f5f5ec"
    base_text_2_dark: "#929eaf"
    primary_bg_dark: "#fdfcf9"
    primary_bg_2_dark: "#fdfcf9"
    primary_bg_3_dark: "#fdfcf9"
    primary_text_dark: "#0b0326"
    header_text_dark: "#fdfcf9"
    logo_text_dark: "#fdfcf9"

  fonts:
    use_google_fonts: false
    google_fonts_url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Roboto:wght@300&display=swap"
    google_fonts_url: "https://fonts.googleapis.com/css2?family=Roboto:wght@200..900&display=swap"
    google_fonts_url: "https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" 

    use_self_hosted_fonts: true # font files must be placed in /static/fonts folder and the @font-face definitions must be added to /static/fonts/fonts.css
    heading: "'CenturyGothic'" 
    base: "'CenturyGothic'"
    monospace: "'CenturyGothic'"
    logo: "'CenturyGothic'"

  logo:
    logo_text: "Gallery"
    logo_image_desktop: images/logo/logo.png
    logo_image_mobile: images/logo/logo-mobile.png
    logo_image_desktop_invert: images/logo/logo-invert.png
    logo_image_mobile_invert: images/logo/logo-invert-mobile.png
    logo_image_desktop_height: "28px"
    # logo_image_desktop_width: "28px"
    logo_image_mobile_height: "28px"
    # logo_image_mobile_width: "28px"
    show_logo_image_on_mobile: true
    show_logo_image_on_desktop: true
    show_logo_text_on_mobile: false
    show_logo_text_on_desktop: true
    logo_text_font_size: "34px"
    logo_text_font_weight: "400"

  header:
    fixed: false
    header_height: "28px"
    header_menu_font_size: "16px"

  # open_graph:
  #   og_type: "website"
  #   og_twitter_card: "summary"
  #   og_twitter_site: "@zerostaticio"
  #   og_twitter_creator: "@zerostaticio"

  dark_mode:
    enable_dark_mode: false
    show_dark_mode_toggle_in_header: false
    show_dark_mode_toggle_in_bottom: false
    show_dark_mode_toggle_in_mobile_menu: false

  cookie_banner:
    enabled: false
    show_manage_cookies_at_bottom: true

  analytics:
    google_analytics_id: "" # G-XXXXXXXXXX

  # newsletter:
  #   mailchimp:
  #     form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
  #     form_title: "Let's keep in touch"

  contact_form:
    use_netlify_form: true
    netlify_form_name: "contact"

  multilingual:
    enable_language_switcher: false
    show_language_switcher_in_header: false

  menu:
    show_dropdown_items_in_mobile_menu: true
    show_social_media_in_mobile_menu: true

  footer:
    enable_footer: true # show/hide the entire footer
    footer_title: "ГАЛЕРИЯ 33"
    footer_description: "“Галерия 33“ е най-новата галерия в сърцето на Варна. Тя отваря врати на 3 март 2024 г. Основателите на галерията, след години опит, решават да създадат свое пространство за модерно и съвременно изкуство. Галерията се намира в централата стара част на Варна на ул. “Габрово” 2А, в прекрасна сграда от началото на миналия век."
    enable_social_media_links: true
    enable_languages: false
    enable_copyright: true
    enable_menu_footer_primary: true
    enable_menu_footer_secondary: true
    enable_menu_footer_tertiary: true
    footer_primary_menu_title: "Работно време"
    footer_secondary_menu_title: "Дейност"
    footer_tertiary_menu_title: "За нас"

  bottom:
    enabled: false # show/hide the entire bottom (below the footer)
    enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
    copyright_text: "Галерия 33, 2024 ©"
    show_rss_icon: true

menu:
  main:
    - name: Изложби
      pageRef: exhibitions
      weight: 1
    - name: Колекция
      identifier: collection
      pageRef: collection
      weight: 2
    - name: Живопис
      pageRef: /genres/живопис
      parent: collection
      weight: 1
    - name: Графика
      pageRef: /genres/графика
      parent: collection
      weight: 2
    - name: Скулптура
      pageRef: /genres/скулптура
      parent: collection
      weight: 3
    - name: Други
      pageRef: /genres/други
      parent: collection
      weight: 4
    - name: Автори
      pageRef: categories/
      weight: 3
    - name: За нас
      pageRef: about
      weight: 4
  footer_primary:
    - name: "Понеделник - Почивен ден"
      weight: 1
    - name: "Вторник - 10:00 - 19:00"
      weight: 2
    - name: "Сряда - 10:00 - 19:00"
      weight: 3
    - name: "Четвъртък - 10:00 - 19:00"
      weight: 4
    - name: "Петък - 10:00 - 19:00"
      weight: 5
    - name: "Събота - 11:00 - 19:00"
      weight: 6     
    - name: "Неделя - Почивен ден"
      weight: 7                             
  footer_secondary:
    - name: "Изложби"
      pageRef: exhibitions
      weight: 1
    - name: "Колекция"
      pageRef: collection
      weight: 2
    # - name: "Патрон 33"
    #   pageRef: patron33
    #   weight: 3
  footer_tertiary:
    - name: Контакти
      pageRef: contact-guest
      weight: 1
    # - name: Пространство
    #   pageRef: space
    #   weight: 3
    # - name: Документи
    #   pageRef: documents
    #   weight: 4
    - name: Общи условия
      pageRef: terms
      weight: 5
    - name: Поверителност
      pageRef: privacy
      weight: 6


permalinks:
  posts: "blog/:year/:month/:title/"
  pages: ":slug/"

taxonomies:
  tag: tags
  category: categories
  genre: genres

markup:
  goldmark:
    renderer:
      unsafe: true
