baseURL: /
title: Hugo Curate

paginate: 6
enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
languageCode: "en-us"
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

params:
  colors:
    # light
    base_bg: "#fdfcf9"
    base_bg_2: "#f7f6ed"
    base_bg_3: "#faebd7"
    base_text: "#0d042b"
    base_text_2: "#3b364c"
    primary_bg: "#0d042b"
    primary_bg_2: "#0d042b"
    primary_bg_3: "#0d042b"
    primary_text: "#fdfcf9"
    header_text: "#0d042b"
    logo_text: "#0d042b"

    # dark
    base_bg_dark: "#0b0326"
    base_bg_2_dark: "#150c32"
    base_bg_3_dark: "#251654"
    base_text_dark: "#f5f5ec"
    base_text_2_dark: "#929eaf"
    primary_bg_dark: "#fdfcf9"
    primary_bg_2_dark: "#fdfcf9"
    primary_bg_3_dark: "#fdfcf9"
    primary_text_dark: "#0b0326"
    header_text_dark: "#fdfcf9"
    logo_text_dark: "#fdfcf9"

  fonts:
    use_google_fonts: false
    google_fonts_url: "https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,500;9..40,700&family=Fira+Mono&display=swap"
    use_self_hosted_fonts: true # font files must be placed in /static/fonts folder and the @font-face definitions must be added to /static/fonts/fonts.css
    heading: "'DM Sans'"
    base: "'DM Sans'"
    monospace: "'Fira Mono'"
    logo: "'DM Sans'"

  logo:
    logo_text: "Hugo Curate"
    logo_image_desktop: images/logo/logo.png
    logo_image_mobile: images/logo/logo-mobile.png
    logo_image_desktop_invert: images/logo/logo-invert.png
    logo_image_mobile_invert: images/logo/logo-invert-mobile.png
    logo_image_desktop_height: "28px"
    logo_image_desktop_width: "28px"
    logo_image_mobile_height: "28px"
    logo_image_mobile_width: "28px"
    show_logo_image_on_mobile: true
    show_logo_image_on_desktop: true
    show_logo_text_on_mobile: false
    show_logo_text_on_desktop: false
    logo_text_font_size: "28px"
    logo_text_font_weight: "500"

  header:
    fixed: false
    header_height: "60px"
    header_menu_font_size: "18px"

  open_graph:
    og_type: "website"
    og_twitter_card: "summary"
    og_twitter_site: "@zerostaticio"
    og_twitter_creator: "@zerostaticio"

  dark_mode:
    enable_dark_mode: true
    show_dark_mode_toggle_in_header: true
    show_dark_mode_toggle_in_bottom: false
    show_dark_mode_toggle_in_mobile_menu: true

  cookie_banner:
    enabled: false
    show_manage_cookies_at_bottom: true

  analytics:
    google_analytics_id: "" # G-XXXXXXXXXX
    gtm_id: "" # GTM-XXXXXXXX
    plausible_data_domain: "" # example: mywebsite.com
    umami_data_website_id: "" # example: "ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b"
    umami_src: "" # "https://analytics.eu.umami.is/script.js"

  comments:
    commento:
      enabled: true # you must have a commento account and be on the correct domain. does not work locally.
    disqus:
      shortname: "" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.

  newsletter:
    mailchimp:
      form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
      form_title: "Let's keep in touch"

  contact_form:
    use_netlify_form: false
    use_formspree_form: true
    formspree_endpoint: https://formspree.io/f/moqyklqv
    netlify_form_name: "contact"

  multilingual:
    enable_language_switcher: true
    show_language_switcher_in_header: true

  menu:
    show_dropdown_items_in_mobile_menu: false
    show_social_media_in_mobile_menu: true

  footer:
    enable_footer: true # show/hide the entire footer
    footer_title: "Hugo Curate"
    footer_description: "Curate is a creative portfolio for Hugo by Zerostatic Themes."
    enable_social_media_links: true
    enable_languages: false
    enable_copyright: false
    enable_menu_footer_primary: true
    enable_menu_footer_secondary: true
    enable_menu_footer_tertiary: false
    footer_primary_menu_title: "Projects"
    footer_secondary_menu_title: "Company"
    footer_tertiary_menu_title: "Support"

  bottom:
    enabled: false # show/hide the entire bottom (below the footer)
    enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
    copyright_text: "© 2023 Zerostatic Themes"
    show_rss_icon: true

menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
    - name: Projects
      pageRef: projects
      weight: 2
      # Projects dropdown menu
    - name: "Project Layout 1"
      pageRef: projects/project-1
      parent: Projects
      weight: 1
      params:
        icon: "images/icons/wireframe-7.svg"
        icon_darkmode: "images/icons/wireframe-7-white.svg"
        description: "Default Project layout"
    - name: "Project Layout 2"
      pageRef: projects/project-2
      parent: Projects
      weight: 2
      params:
        icon: "images/icons/wireframe-5.svg"
        icon_darkmode: "images/icons/wireframe-5-white.svg"
        description: "Right side layout"
    - name: "Project Layout 3"
      pageRef: projects/project-3
      parent: Projects
      weight: 3
      params:
        icon: "images/icons/wireframe-6.svg"
        icon_darkmode: "images/icons/wireframe-6-white.svg"
        description: "Left side layout"
    - name: "Project Layout 4"
      pageRef: projects/project-4
      parent: Projects
      weight: 4
      params:
        icon: "images/icons/wireframe-8.svg"
        icon_darkmode: "images/icons/wireframe-8-white.svg"
        description: "Top layout"
    - name: Blog
      pageRef: posts
      weight: 3
    - name: About
      pageRef: about
      weight: 4
    - name: Contact
      pageRef: contact
      weight: 5
  footer_primary:
    - name: "Project 1"
      pageRef: projects/project-1
      weight: 1
    - name: "Project 2"
      pageRef: projects/project-2
      weight: 2
    - name: "Project 3"
      pageRef: projects/project-3
      weight: 3
    - name: "Project 4"
      pageRef: projects/project-4
      weight: 4
  footer_secondary:
    - name: Blog
      pageRef: posts
      weight: 1
    - name: About
      pageRef: about
      weight: 2
    - name: Contact
      pageRef: contact
      weight: 3
    - name: Privacy Policy
      pageRef: privacy
      weight: 4
    - name: Terms and Conditions
      pageRef: terms
      weight: 5
  bottom:
    - name: Privacy Policy
      pageRef: privacy-policy
      weight: 1
    - name: Terms and Conditions
      pageRef: terms-and-conditions
      weight: 2

permalinks:
  posts: "blog/:year/:month/:title/"
  pages: ":slug/"

taxonomies:
  tag: tags
  category: categories
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true
