baseURL: /
title: Галерия 33

paginate: 6
enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
languageCode: "bg"
defaultContentLanguage: bg
defaultContentLanguageInSubdir: false

params:
  colors:
    # light
    base_bg: "#fdfcf9"
    base_bg_2: "#f7f6ed"
    base_bg_3: "#faebd7"
    base_text: "#0d042b"
    base_text_2: "#3b364c"
    primary_bg: "#0d042b"
    primary_bg_2: "#0d042b"
    primary_bg_3: "#0d042b"
    primary_text: "#fdfcf9"
    header_text: "#0d042b"
    logo_text: "#0d042b"

    # dark
    base_bg_dark: "#0b0326"
    base_bg_2_dark: "#150c32"
    base_bg_3_dark: "#251654"
    base_text_dark: "#f5f5ec"
    base_text_2_dark: "#929eaf"
    primary_bg_dark: "#fdfcf9"
    primary_bg_2_dark: "#fdfcf9"
    primary_bg_3_dark: "#fdfcf9"
    primary_text_dark: "#0b0326"
    header_text_dark: "#fdfcf9"
    logo_text_dark: "#fdfcf9"

  fonts:
    use_google_fonts: false
    google_fonts_url: "https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,500;9..40,700&family=Fira+Mono&display=swap"
    use_self_hosted_fonts: true # font files must be placed in /static/fonts folder and the @font-face definitions must be added to /static/fonts/fonts.css
    heading: "'Inter'"
    base: "'Inter'"
    monospace: "'Inter'"
    logo: "'Inter'"

  logo:
    logo_text: "ГАЛЕРИЯ"
    logo_image_desktop: images/logo/logo.png
    logo_image_mobile: images/logo/logo-mobile.png
    logo_image_desktop_invert: images/logo/logo-invert.png
    logo_image_mobile_invert: images/logo/logo-invert-mobile.png
    logo_image_desktop_height: "28px"
    # logo_image_desktop_width: "28px"
    logo_image_mobile_height: "28px"
    # logo_image_mobile_width: "28px"
    show_logo_image_on_mobile: true
    show_logo_image_on_desktop: true
    show_logo_text_on_mobile: false
    show_logo_text_on_desktop: true
    logo_text_font_size: "28px"
    logo_text_font_weight: "500"

  header:
    fixed: false
    header_height: "60px"
    header_menu_font_size: "18px"

  open_graph:
    og_type: "website"
    og_twitter_card: "summary"
    og_twitter_site: "@zerostaticio"
    og_twitter_creator: "@zerostaticio"

  dark_mode:
    enable_dark_mode: false
    show_dark_mode_toggle_in_header: false
    show_dark_mode_toggle_in_bottom: false
    show_dark_mode_toggle_in_mobile_menu: false

  cookie_banner:
    enabled: false
    show_manage_cookies_at_bottom: true

  analytics:
    google_analytics_id: "" # G-XXXXXXXXXX

  newsletter:
    mailchimp:
      form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
      form_title: "Let's keep in touch"

  contact_form:
    use_netlify_form: true
    netlify_form_name: "contact"

  multilingual:
    enable_language_switcher: false
    show_language_switcher_in_header: false

  menu:
    show_dropdown_items_in_mobile_menu: false
    show_social_media_in_mobile_menu: true

  footer:
    enable_footer: true # show/hide the entire footer
    footer_title: "ГАЛЕРИЯ 33"
    footer_description: "Галерия 33, разположена във Варна, представя изключителна колекция от изящни изкуства. С фокус върху изисканите творби, галерията предлага завладяващо пътуване из света на изящните изкуства. Нейният уебсайт предоставя възможността да се насладите на богатството от изкуство."
    enable_social_media_links: true
    enable_languages: false
    enable_copyright: true
    enable_menu_footer_primary: true
    enable_menu_footer_secondary: true
    enable_menu_footer_tertiary: false
    footer_primary_menu_title: "Дейност"
    footer_secondary_menu_title: "За нас"
    footer_tertiary_menu_title: "Support"

  bottom:
    enabled: false # show/hide the entire bottom (below the footer)
    enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
    copyright_text: "Галерия 33, 2024 ©"
    show_rss_icon: true

menu:
  main:
    - name: Изложби
      pageRef: exhibitions
      weight: 1
    - name: Колекция
      pageRef: collection
      weight: 2
    - name: Дейност
      pageRef: about
      weight: 4
  footer_primary:
    - name: "Изложби"
      pageRef: exhibitions
      weight: 1
    - name: "Колекция"
      pageRef: collection
      weight: 2
    - name: "Патрон 33"
      pageRef: patron33
      weight: 3
  footer_secondary:
    - name: Контакт
      pageRef: contact-guest
      weight: 1
    - name: Пространство
      pageRef: space
      weight: 3
    - name: Документи
      pageRef: documents
      weight: 4
    - name: Уловия и права
      pageRef: terms
      weight: 5
    - name: Поверителност
      pageRef: privacy
      weight: 6

permalinks:
  posts: "blog/:year/:month/:title/"
  pages: ":slug/"

taxonomies:
  tag: tags
  category1: categories


markup:
  goldmark:
    renderer:
      unsafe: true
