[context.production.environment]
  HUGO_VERSION = "0.102.3"
  HUGO_GOOGLE_ANALYTICS_ID = "GA-XX"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.102.3"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.102.3"
  
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "client"
