backend:
  name: git-gateway
  branch: develop
local_backend: true 
logo_url: https://gallery33.art/images/favicon/favicon.png
 # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
media_folder: "static/images/uploads"


collections:
  - name: "exhibition"
    label: "Изложби"
    folder: "content/exhibitions"
    create: true
    slug: "{{slug}}-{{year}}{{month}}{{day}}{{minute}}{{second}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "exhibition"}
      - {label: "Име на изложбата", name: "title", widget: "string"}
      - {label: "Участници в изложбата", name: "artist", widget: "list", field: {label: "Артист", name: "category", widget: "string"}}
      - {label: "Продължителност на изложбата", name: "when", widget: "string"}
      - {label: "Дата на поста", name: "date", widget: "datetime"}
      - {label: "представя (попълва се с 1 само за случващи се излложби)", name: "ongoing", widget: "string"}
      - {label: "Изображение меню", name: "thumbnail", widget: "image"}
      - {label: "Изображение(я) страница", name: "gallery", widget: "list", fields: [
          {label: "Image", name: "image", widget: "image"}
        ]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "art-piece"
    label: "Колекция"
    folder: "content/collection"
    create: true
    preview_path: "collection/{{slug}}-{{year}}-{{month}}-{{day}}-{{minute}}-{{second}}"
    slug: "{{slug}}-{{year}}{{month}}{{day}}{{minute}}{{second}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "art-piece"}
      - {label: "Наименование", name: "title", widget: "string"}
      - {label: "Автор(и)", name: "categories", widget: "list", field: {label: "Автор", name: "category", widget: "string"}}
      - {label: "Вид(ове)", name: "genres", widget: "list", field: {label: "Вид", name: "genre", widget: "string"}}
      - {label: "Година на изработка", name: "year", widget: "string"}
      - {label: "Техника(и)", name: "tags", widget: "list", field: {label: "Техника", name: "tag", widget: "string"}}
      - {label: "Размер", name: "size", widget: "string"}
      - {label: "Изображение меню ЗАДЪЛЖИТЕЛНО", name: "thumbnail", widget: "image"}
      - {label: "Изображение(я) страница ЗАДЪЛЖИТЕЛНО", name: "gallery", widget: "list", fields: [
          {label: "Image", name: "image", widget: "image"}
        ]}
      - {label: "Дата на поста", name: "date", widget: "datetime"}
      - {label: "Допълнителен текст", name: "body", widget: "markdown"}
      - {label: "Дали е продадена (true/false)", name: "sold", widget: "boolean"}

  - name: "pages"
    label: "About Us"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}




