backend:
  name: git-gateway
  branch: main 
  
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "exhibition"
    label: "Exhibition"
    folder: "_posts/exhibition"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "exhibition"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Gallery Limit", name: "gallery_limit", widget: "number"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Gallery", name: "gallery", widget: "list", fields: [
          {label: "Image", name: "image", widget: "image"}
        ]}

  - name: "art-piece"
    label: "Art Piece"
    folder: "_posts/art-piece"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "art-piece"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "list", field: {label: "Author", name: "author", widget: "string"}}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list", field: {label: "Category", name: "category", widget: "string"}}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Gallery", name: "gallery", widget: "list", fields: [
          {label: "Image", name: "image", widget: "image"}
        ]}
